name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make test_ci

      - uses: mshick/add-pr-comment@v2.8.2
        with:
          message-path: ${{ github.workspace }}/test.out
